# Generated by Django 4.2.8 on 2023-12-13 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0002_alter_question_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255)),
                ('parameters', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_time', models.FloatField(blank=True, default=None, null=True)),
                ('energy_usage', models.FloatField(blank=True, default=None, null=True)),
                ('memory_usage', models.FloatField(blank=True, default=None, null=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='llm.model')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='llm.question')),
            ],
        ),
    ]
