# Generated by Django 4.2.8 on 2023-12-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0003_model_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='model_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='parameters',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
